### PR TITLE
SVG and improved PNG for Chrome

### PR DESCRIPTION
**Pull request by zg**
I found an SVG of the Chrome logo (provided by [Wikipedia, Public Domain](https://en.wikipedia.org/wiki/File:Google_Chrome_icon_(2011).svg)) and, based on that, created a new PNG for the Chrome logo running the following command: `qlmanage -t -s 2048 -o . chrome.svg`

### CODE REVIEW

**Comment by alrra** [comment]
@zg Thanks for the pull request.

--

> I found an SVG of the Chrome logo (provided by Wikipedia, Public Domain)

@zg The `SVG` is different from [the logo from this repository](https://github.com/alrra/browser-logos/issues/34) (which is kinda the official one):

| Image from this repository | Image generate from the SVG | Difference |
|:---:|:---:|:---:|
|  |  |  |

-- 

@paulirish For most of the top browsers, this repository provides a SVG version of the logo, but unfortunately, that is not the case with Chrome. Can you help in this regard? Thanks!

**Comment by zg** [comment]
How'd you generate that difference image?  Interesting.

**Comment by alrra** [comment]
> How'd you generate that difference image? Interesting.

@zg I've used [ImageMagick's compare](http://www.imagemagick.org/script/compare.php) command-line tool:

```bash
compare a.png b.png -compose src c.png 
```

**Comment by zg** [comment]
Good to know.  I'm curious of the source of the image in this repository.  Perhaps that should be re-considered.  The SVG I provided looks good, but perhaps I am wrong.

**Comment by alrra** [comment]
>  I'm curious of the source of the image in this repository

@zg See https://github.com/alrra/browser-logos/issues/34.

> Perhaps that should be re-considered. 

@zg Yes, it should, that's why I basically Cc @paulirish.

--

@paulirish Even the logo provided with Chrome (OS X) is now a little bit different from the one from this repository.

| Image from this repository | Image provided with<br>Chrome (OS X) | Difference |
|:---:|:---:|:---:|
|  |  |  |

**Comment by paulirish** [comment]
the wikipedia SVG is fanart: https://github.com/johan/kilobyte-svg-challenge/commit/611d7feea99cdd1dc70787c4dd03e1a7bf0bf993
we could use it, i suppose. but it's not official. (Not sure if we have other non-official SVGs)

I think the one from this repo is a little old now and does appear to be different than what ships with OSX. I am asking for an updated version internally. hard to track down, surprisingly.

**Comment by alrra** [comment]
> I am asking for an updated version internally. hard to track down, surprisingly.

Thanks @paulirish!

**Comment by alrra** [comment]
> the wikipedia SVG is fanart: 

@zg Thanks for the pull request, but I'm going to close this as the SVG is noticeably different from the official one. :)

> I am asking for an updated version internally. hard to track down, surprisingly.

@paulirish If you find something, feel free to open a pull request. 

--

> the one from this repo is a little old now and does appear to be different than what ships with OSX. 

@paulirish  I've [updated the Chrome logos](https://github.com/alrra/browser-logos/blob/e06a6d69cd544b4dc13d9227b37481bb52b9bb72/CHANGELOG.md#880-march-24-2015).

**Pull request closed without merging**
