### PR TITLE
Adding SVG Version of Vivaldi Icon

### PR DESCRIPTION
**Pull request by atlemo**
Adding the Official Vivaldi Icon in SVG format, as this was missing.

### CODE REVIEW

**Comment by atlemo** [comment]
Any insight as to why this would fail the checks?

**Comment by alrra** [comment]
@atlemo Thanks for this PR, and sorry for the delay on it!

> Any insight as to why this would fail the checks?

Some links are broken, not related to your PR.

**Comment by alrra** [comment]
@atlemo Any change you can also provide the SVG version also for [`vivaldi-snapshot`]( https://github.com/alrra/browser-logos/tree/a49e24b1103e2eabddbd56e9d24305725e0b4500/src/vivaldi-snapshot)? Thanks!

**Comment by alrra** [comment]
@atlemo I published a [new version](https://www.npmjs.com/package/@browser-logos/vivaldi) of the logo. Thanks again!

**Pull request closed without merging**
