### PR TITLE
Add Polypane browser

### PR DESCRIPTION
**Pull request by Kilian**
Hi! I've added the logo for [Polypane](https://polypane.rocks).

### CODE REVIEW

**Comment by Kilian** [comment]
Hmm :thinking: the URL's on this page: https://github.com/alrra/browser-logos/pull/173/files#diff-3ef187c218e4fd11f5ae9d8870c74303R6 causing the test to fail is kind of a catch-22. How should I deal with that?

**Comment by alrra** [comment]
>  How should I deal with that?

No. That part is [automatically generated before publishing](https://github.com/alrra/browser-logos/blob/42d3403384d4a69f5d2606060e0b79c66f4fc2ab/scripts/prepare-for-publishing.js#L56). Sorry about the confusion.

---

@Kilian These days there are a lot of new Chromium / WebKit based browsers being created that are rarely if ever updated / worked upon over time. So, a while ago I decided to not include browsers if they don't have any historical significance (e.g. Mosaic), have some significant market share, etc. 

For the time being I will pass on this one, but this browser has an interesting approach to things, I am curious how it will evolve over time.

**Comment by Kilian** [comment]
So you just add a directory with images and the script does the rest?

---
I get your reasoning. Polypane is my company though, so I have some interest in keeping it updated and I'm working on it all the time :) I hope you'll reconsider, now or in the future!

**Comment by alrra** [comment]
> So you just add a directory with images and the script does the rest?

@Kilian Yes.

> I hope you'll reconsider

Change is the only constant in life, so I do [reconsider things](https://github.com/alrra/browser-logos/commit/189fb0cc6f743c0e982d1fca372defe6f3a63dbc#diff-fcdbaf933011a89ff6b0de72c517e44e) all the time.

**Comment by Kilian** [comment]
Hey @alrra! I recently updated the logo for Polypane and wanted to check if you'd consider adding it at this point, to also make it easier for @will-stone to use in Browserosaurus.

**Comment by Kilian** [comment]
Three years along and Polypane is still going strong: https://polypane.app/docs/changelog/ 

@alrra would you be open to a new PR with the most recent set of icons?

**Pull request closed without merging**
