### PR TITLE
Feat: add electron icons

### PR DESCRIPTION
**Pull request by blade254353074**

### CODE REVIEW

**Comment by alrra** [comment]
@blade254353074  Thanks for opening this PR!

---

Don't know if we should add this or not. :/

Any other opinions?

**Comment by blade254353074** [comment]
Because it's similar with `NW.js`, so I think we should add this~

**Comment by mathiasbynens** [comment]
👍  Add it!

**Comment by blade254353074** [comment]
Hi, can we merge it?

**Comment by alrra** [comment]
> can we merge it?

@blade254353074 I will, just that I didn't have the time to look over it yet.

**Comment by alrra** [comment]
Thanks, @blade254353074!

**Comment by blade254353074** [comment]
You are welcome

**Pull request closed without merging**
