### PR TITLE
Redraw IE9 SVG to get from 600+KB to 8.5KB

### PR DESCRIPTION
**Pull request by eoghanmurray**
Original was 100x the file size.
I'm comparing an export of this redraw against the 512x512px .png version and there's not much in it

### CODE REVIEW

**Comment by eoghanmurray** [comment]
ie-compare

**Comment by eoghanmurray** [comment]
ie-compare

**Comment by eoghanmurray** [comment]
ie-compare-old

I'm taking certain things in this old SVG to be artefacts — e.g. the extra yellow border above swoosh, and the lack of blue colour at top right

**Comment by alrra** [comment]
@eoghanmurray Great work! Thank you for doing this! 

---

Here is the comparison view:




At first glance 2 main differences stand out to me:

* The bottom of the ring:

   

* The darker yellow part of the ring (it needs to be less):

**Comment by alrra** [comment]
@eoghanmurray You are getting really close! 👏

Here is the [diff view](https://github.com/alrra/browser-logos/pull/202/files?short_path=167afd8#diff-167afd8349561818552e0aafc9ec9bff8accb0c4b44cd69760eb8da24c859f6b):

https://user-images.githubusercontent.com/1223565/134116573-7458fa26-6673-4d1a-b614-284953d39e2a.mp4

The darker yellow part of the ring still stands out as the main difference. 

Also, very minor things: 

* The length of the shadow underneath the ring needs to be increased a bit.
* The parts of the ring right before they go underneath the e should be a bit more transparent?

**Comment by eoghanmurray** [comment]
Ok loads more work done, basically redrew the 'swoosh' again, with probably about 6 complex and independent gradients rather than the 2 or 3 simpler ones in the previous version.  Don't think I'm gonna get better than this as my reference .png is looking very close now; but maybe you have a different reference image which can uncover any further tweaks that are necessary?

**Comment by eoghanmurray** [comment]
ie-compare

This gif isn't the whole story as I think it introduces some artefacts in the raster of the svg due to reduced colour space maybe.

**Comment by alrra** [comment]
@eoghanmurray Thank you! 🙇‍♂️

---

> This gif isn't the whole story as I think it introduces some artefacts in the raster of the svg due to reduced colour space maybe.

Note: You can use GitHub to compare the differences. 

https://user-images.githubusercontent.com/1223565/135119693-56b70a46-bc2f-4e02-9d18-0dc7ae2d13c5.mp4

> as my reference .png

What PNG are you using?

> maybe you have a different reference image which can uncover any further tweaks that are necessary?

Note: In this repository the image without any dimensions included in the filename is the biggest one dimensionwise and the best one when it comes to details. In the case of IE 9-11, that image would be [this one](https://github.com/alrra/browser-logos/blob/5b8bfea091f7bb2dae9155d7c18382c1566fe440/src/archive/internet-explorer_9-11/internet-explorer_9-11.png).

For logos for which this project has the SVG, the SVG would be the best reference. As you previously notice, the PNG images are generated from the SVG.

**Comment by eoghanmurray** [comment]
Was wondering how you generated the previous 'swipe' video!

> the PNG images are generated from the SVG.
I thought I noticed some serious artefacts in the prior SVG, as can be seen in this comparison:
https://github.com/alrra/browser-logos/pull/202#issuecomment-918629422
e.g. SVG had a much darker blue in top left segment 
Therefore I didn't think the pngs were ever generated from that SVG. Maybe they were all provided at once by that member of the IE team?

**Comment by alrra** [comment]
> e.g. SVG had a much darker blue in top left segment
> Therefore I didn't think the pngs were ever generated from that SVG.

@eoghanmurray Could it be that the software (i.e.: Inkscape) you open the SVG in doesn't render it correctly? Try opening [the SVG image](https://github.com/alrra/browser-logos/files/7247843/svg.zip) in a browser?

Here is the latest [PNG](https://github.com/alrra/browser-logos/blob/5b8bfea091f7bb2dae9155d7c18382c1566fe440/src/archive/internet-explorer_9-11/internet-explorer_9-11.png) and here is the latest [SVG](https://github.com/alrra/browser-logos/blob/5b8bfea091f7bb2dae9155d7c18382c1566fe440/src/archive/internet-explorer_9-11/internet-explorer_9-11.svg). I don't see any difference related to the blue background, and almost no difference overall: 

https://user-images.githubusercontent.com/1223565/135174726-7f76fb98-12c6-4b13-a6c9-fccf48342c4f.mp4

Note: I think the barely noticeable minor ring gradient differences come from resizing the SVG to be the same size as the PNG.

---

Even though only lossless optimizations were done on `internet-explorer_9-11.svg` since the PNGs were generated, I [regenerated them again](https://github.com/alrra/browser-logos/commit/fef1574b255fe078912d1ecfbb460219b68f2e22).

**Comment by eoghanmurray** [comment]
> Could it be that the software (i.e.: Inkscape) you open the SVG in doesn't render it correctly? Try opening the SVG image in a browser?

Ah yes that was it! Previous version renders fine in [certain sizes](https://github.com/alrra/browser-logos/blob/17acb075d41f15455dc6735316af3ba7507e49ed/src/archive/internet-explorer_9-11/internet-explorer_9-11.svg) in the browser, but actually none of the gradients show when [viewed raw](https://raw.githubusercontent.com/alrra/browser-logos/17acb075d41f15455dc6735316af3ba7507e49ed/src/archive/internet-explorer_9-11/internet-explorer_9-11.svg).  Also in Inkscape it doesn't render correctly which I didn't realize at the time.  Good job I restarted comparing against the .png!

So defo the new version I've done is much better I think!

I'm attaching the 'full' Inkscape file in case anyone wants to use that for a further rework, which includes an embedded png for comparison, but otherwise the optimized SVG should be editable as I've labelled all the gradients/masks intelligibly. 

[internet-explorer_9-11.inkscape.zip](https://github.com/alrra/browser-logos/files/7251088/internet-explorer_9-11.inkscape.zip)

**Comment by alrra** [comment]
> Previous version renders fine in certain sizes in the browser

@eoghanmurray Yes, use the view inside of github.com or just open the file directly from your computer. 

> but actually none of the gradients show when viewed raw.

@eoghanmurray That is because on the raw page all the embedded images are blocked by the [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) policy.

**Comment by eoghanmurray** [comment]
Any other issues before this can be accepted?

**Comment by alrra** [comment]
@eoghanmurray Great work! 👏 Again, thank you for working on this!

**Comment by alrra** [comment]
@eoghanmurray This PR is now merged in: https://github.com/alrra/browser-logos/commit/afce2bfaaa8d9783fe68c969ed52502ffe5060ae.

**Pull request closed without merging**
