### PR TITLE
Added SVGs for Old IE

### PR DESCRIPTION
**Pull request by scribblemaniac**
The developer channel logo is converted from the eps file provided in #48. The IE 9-11 logo is just that svg file with the extra objects deleted. I did not optimized either of them.

### CODE REVIEW

**Comment by KIPdeKIP** [comment]
It's worth mentioning that the logo is a combination of vectors and large raster images, making it a pretty big file.

It should definitely get added imo. A vector image's filesize doesn't matter, it's always smaller then the infinite number of raster images that can be made from it.

**Comment by alrra** [comment]
Thanks, @scribblemaniac! 

> It's worth mentioning that the logo is a combination of vectors and large raster images, making it a pretty big file.

@KIPdeKIP Yes, that was the main reason why I didn't added it in the first place. I thought that maybe someone figures a way around that. 

> making it a pretty big file.
>  I did not optimized either of them.

Optimized them and managed to reduce the size a bit. :)

**Comment by KIPdeKIP** [comment]
Thanks for adding it. Were the data URIs optimized as well?

Saved the first data URI and was able to losslessly compress it reducing its size by about 50%. (PNGGauntlet) But I'm not sure if I got the exact URI or if it got resaved uncompressed.

**Comment by alrra** [comment]
> Were the data URIs optimized as well?

@KIPdeKIP Yes, extracted, losslessly optimized, and readded them in.

**Pull request closed without merging**
